### ISSUE TITLE
Termux: Linker cannot find symbols

### ISSUE THREAD

**Issue by IntinteDAO** [mltframework/mlt#1003]
I am not giga strong in C++, but somehow I manage to compile programs.

I want to try (as much as possible) to port the shotcut application to Termux. Termux is a Linux environment running on Android, using Android libraries like Bionic Libc and so on.

The compiler is Clang, the processor architecture is aarch64 (aarch64-unknown-linux-android).

The compilation seems to go through without problems, however, I get errors at the linker stage

MLT: 7.24.0

~/mlt-7.24.0/build $ make
[  1%] Linking C shared library ../../out/lib/libmlt-7.so
ld.lld: error: version script assignment of 'MLT_0.8.8' to symbol 'mlt_frame_get_alpha_mask' failed: symbol not defined
ld.lld: error: version script assignment of 'MLT_0.8.8' to symbol 'mlt_geometry_close' failed: symbol not defined
ld.lld: error: version script assignment of 'MLT_0.8.8' to symbol 'mlt_geometry_fetch' failed: symbol not defined
ld.lld: error: version script assignment of 'MLT_0.8.8' to symbol 'mlt_geometry_get_length' failed: symbol not defined
ld.lld: error: version script assignment of 'MLT_0.8.8' to symbol 'mlt_geometry_init' failed: symbol not defined
ld.lld: error: version script assignment of 'MLT_0.8.8' to symbol 'mlt_geometry_insert' failed: symbol not defined
ld.lld: error: version script assignment of 'MLT_0.8.8' to symbol 'mlt_geometry_interpolate' failed: symbol not defined
ld.lld: error: version script assignment of 'MLT_0.8.8' to symbol 'mlt_geometry_next_key' failed: symbol not defined
ld.lld: error: version script assignment of 'MLT_0.8.8' to symbol 'mlt_geometry_parse' failed: symbol not defined
ld.lld: error: version script assignment of 'MLT_0.8.8' to symbol 'mlt_geometry_parse_item' failed: symbol not defined
ld.lld: error: version script assignment of 'MLT_0.8.8' to symbol 'mlt_geometry_prev_key' failed: symbol not defined
ld.lld: error: version script assignment of 'MLT_0.8.8' to symbol 'mlt_geometry_refresh' failed: symbol not defined
ld.lld: error: version script assignment of 'MLT_0.8.8' to symbol 'mlt_geometry_remove' failed: symbol not defined
ld.lld: error: version script assignment of 'MLT_0.8.8' to symbol 'mlt_geometry_serialise' failed: symbol not defined
ld.lld: error: version script assignment of 'MLT_0.8.8' to symbol 'mlt_geometry_serialise_cut' failed: symbol not defined
ld.lld: error: version script assignment of 'MLT_0.8.8' to symbol 'mlt_geometry_set_length' failed: symbol not defined
ld.lld: error: version script assignment of 'MLT_0.8.8' to symbol 'mlt_playlist_move_region' failed: symbol not defined
ld.lld: error: version script assignment of 'MLT_0.8.8' to symbol 'mlt_sample_calculator' failed: symbol not defined
ld.lld: error: version script assignment of 'MLT_0.8.8' to symbol 'mlt_sample_calculator_to_now' failed: symbol not defined
ld.lld: error: version script assignment of 'MLT_0.9.10' to symbol 'mlt_properties_to_utf8' failed: symbol not defined
ld.lld: error: too many errors emitted, stopping now (use --error-limit=0 to see all errors)

**Do you know of any solution?**

**Comment by ddennedy** [comment]
The problem is that the file [`mlt.vers`](https://github.com/mltframework/mlt/blob/master/src/framework/mlt.vers) still includes the symbols that were removed when we last did a breaking, major version change and removed them. The docs I was reading about symbol versioning did not make it clear what to do about that situation, and gcc's `ld` did not complain. I do not have this problem when building with clang on macOS or Windows/arm64, but maybe they are not instructing its linker to include symbol versioning. There is also a `mlt++.vers` file that will likely trigger these. 
The man page for [`lld.ld`](https://man.archlinux.org/man/extra/lld/ld.lld.1.en#undefined-version) says there is an option `--undefined-version` that might remedy this. I think you can include it in the `LDFLAGS` environment variable when configuring the build.
Interestingly, the GNU linker seems to have a [similar option](https://man.archlinux.org/man/ld.1#no~22) with the opposite behavior (opt into treating as error)! I plan to remove these symbols from the version scripts to resolve this, but these options are hints that you can try to resolve in your package build definition.
