### ISSUE TITLE
how can i save the audio language

### ISSUE THREAD

**Issue by damingchuanqi** [mltframework/mlt#1010]
how can i save the audio language

i use this filter

<filter id="filter11">
  <property name="mlt_service">avfilter.ametadata</property>
  <property name="av.key">language</property>
  <property name="av.value">eng</property>
</filter>

But it didn't take effect

I also tried metadata and avformat.alang, but they didn't take effect

**Comment by ddennedy** [comment]
consumer avformat `alang` fixed in 3331639. I do not think filter `avfilter.ametadata` works because that affects FFmpeg's `AVStream`, and MLT does not have AVStreams. AVFilters are exposed generically and often need to be explicitly excluded, and we do not audit them against the frequent changes in FFmpeg filters.
