### ISSUE TITLE
luma option in composite transition seems not working

### ISSUE THREAD

**Issue by myme5261314** [mltframework/mlt#1019]
This tracker is for defects only! For feature requests, you can submit a pull
request with the changes.

If you’re reporting a defect, make it as detailed as possible, and include both your operating system and MLT versions (e.g. `macOS 10.16; MLT v7.4.0`).

OSX 13.6.9 MLT v7.24.0

Any idea why luma option doesn't work properly as described in the document?

```
luma
title: Luma map
description: The luma map file name. If not supplied, a dissolve.
type: string
readonly: no
required: no
widget: fileopen
```
https://www.mltframework.org/plugins/TransitionComposite/#luma

```shell
melt color:white out=250 -track color:blue out=250 -filter affine transition.rect=100/100:100x100 -transition composite luma="" -consumer avformat:composite_luma.mp4
```

https://github.com/user-attachments/assets/42430d9d-3cfe-4932-b00a-490ee110b477

```shell
melt color:white out=250 -track color:blue out=250 -filter affine transition.rect=100/100:100x100 -transition luma -consumer avformat:composite_luma.mp4
```

https://github.com/user-attachments/assets/830b1a7a-4f7c-4c69-9d0c-4a8c9d6f6fe1

**Comment by ddennedy** [comment]
`luma` property works but arguably not the "If not supplied, a dissolve" part. I think this is a documentation error. I do not recall it ever doing a dissolve automatically. That is why for [over 20 years](https://github.com/mltframework/mlt/blob/master/demo/mlt_fade_in_and_out) `demo/mlt_fade_in_and_out` has served as an example of how to do a dissolve transition using the `luma` transition. In order to do a dissolve with `composite` one must keyframe the opacity of `geometry`. The documentation is poorly stating that, not specifying a `luma` allows the opacity to work as expected. In other words, specifying` luma` overrides `opacity`.

The following works to make a dissolve using composite:
`melt noise: out=74 -track -blank 49 color:blue out=149 -transition composite geometry="0=0/0:100%x100%:0%; -1=0/0:100%x100%:100%" in=50 out=74`

The following works to make a horizontal bar wipe (the keyframed opacity is ignored, the two do not combine):
`melt noise: out=74 -track -blank 49 color:blue out=149 -transition composite geometry="0=10%/10%:10%x10%:0%; -1=10%/10%:10%x10%:100%" luma=luma1.pgm in=50 out=74`

I no longer maintain `composite` for it having a poor image and code quality, and I strongly discourage its usage. I do not use it in Shotcut. Also, using `affine` in conjunction with `composite` is weird when you can simply use the `affine` *transition*, where, again, if you want to fade in something atop another keyframe the `rect` opacity.

**Comment by ddennedy** [comment]
I updated the documentation to remove the misleading line.
