### ISSUE TITLE
Show current timestamp in command-line `melt`

### ISSUE THREAD

**Issue by techtonik** [mltframework/mlt#122]
Is it possible to output timestamp along with the frame name in command line client? Maybe with some keyboard shortcut?

**Comment by bmatherly** [comment]
I'm not sure what "timestamp" you are referring to, but it is not possible to output a timestamp. The "-progress" flag will output the progress as a percentage.
Full documentation here:
https://www.mltframework.org/bin/view/MLT/MltMelt

Please do not post support questions on the issue tracker.
https://www.mltframework.org/bin/view/MLT/OnlineSupport

**Comment by techtonik** [comment]
So should I fill it again as a feature request then? Progress is not helpful - I need exact 00:00:02.234 information about current frame. Useful for scripting.

SourceForge mailing list is awful, a pity that you've had to kill discourse.

**Comment by bmatherly** [comment]
Sorry, I didn't mean to disappoint you. The problem is that we are operating with a very small set of volunteers. So we try to be efficient with our time.

* The issue tracker is for bugs that can be reproduced. This allows us to efficiently target bugs without extra clutter in the tracker.
* The mailing list is for general comments and support. It has the widest audience and is most likely to capture a discussion.
* Stackoverflow is great for support requests because at least I get credit when I answer a question there.
* Feature requests are not generally accepted, but you can make an appeal on the mailing list.

Here is my advice for you if you want someone to pay attention to you (this is generally true for most FOSS projects):

1. Use the communication tools requested by the project coordinators
2. Express some gratitude or appreciation.
3. Provide context around your request. Are you using the project to support another compelling open source project? Are you looking to hire someone to add a feature for your commercial project? Is the project being used for a charitable organization that could not otherwise afford to purchase commercial software? Help us know why we should give our time to you and not someone else.
4. Explain what you are trying to accomplish rather than making a specific request. There might be a different way to accomplish your goal that you haven't thought of.

Cheers,
Brian

**Comment by techtonik** [comment]
You may want to add guidelines to this repository to https://help.github.com/articles/setting-guidelines-for-repository-contributors/

The context around my request is that I needed to measure response time of Midnight Commander, so I
1. recorded a video of `mc` scrolling with stopwatch - https://github.com/techtonik/testbin/blob/master/video/mcspeed.webm
2. then tried to find frame when scrolling started and ended with VLC and run into this bug - https://trac.videolan.org/vlc/ticket/17295
3. after spending some time with http://addons.videolan.org/content/show.php/Jump+to+time+(Previous+frame)+v2.1?content=156396 I decided to find an alternative, because it was so painful
4. in the process I noticed that recorded video plays somewhat faster, i.e. time shown on stopwatch skips more seconds that VLC timeline
5. I decided to look for alternative and found this - https://softwarerecs.stackexchange.com/questions/6907/video-player-with-backward-frame-by-frame-stepping-for-linux
6. tried melt, liked the command line interface, but couldn't find how to see timestamps
7. filled this bugreport
8. got back to VLC where I could least somehow get timestamps
9. gathered data
10. found desmos.com, built regression to find that video is sped up by 3.6 time and filled bug for recordscreen https://github.com/cessen/recordscreen/issues/13

**Comment by techtonik** [comment]
Also downloaded Shortcut. Previously I used OpenShot and I it was a little sluggish. )
