### ISSUE TITLE
Regular audio artifacts with wav to wav export

### ISSUE THREAD

**Issue by hamoid** [mltframework/mlt#124]
I'm having audio artifacts with a wav file. I'm using melt 6.2.0 on 64bit Archlinux.

I posted a minimal project, with the source audio file and the resulting glitchy audio file:
https://hamoid.com/mlt-error-example.zip

You can hear the source file does not glitch but the produced one does. I attached screenshots of audacity, comparing the source with the produced audio files. The spectrograms shows regular glitches at about 0.033 second interval. The waveform, I tried to find the discontinuity, but I'm not sure it's the part I show in the image which produces the audio artifact.

Anything I can do to work around this?

**Comment by ddennedy** [comment]
See also https://sourceforge.net/p/mlt/bugs/98/
A patch for this is welcomed.

**Comment by ddennedy** [comment]
Since you know more quickly how to analyze the problem (I have bad hearing and cannot hear the glitch), can you please make a quick test? Edit the .mlt XML file to remove lines from <transition> through </transition> and re-render it. That will help narrow down some things. Also, I see you are upsampling: 44.1 -> 48 KHz. Another quick test is to output 44.1 KHz to see if the problem goes away or is different. Once you do that, there is another couple of tests. Where MLT is installed, first make a backup copy of $prefix/share/mlt/core/loader.ini. Next, comment out the audio filter lines, one at a time: "channels=..." and "resampler=..." to see if that eliminates the problem.

With all of that done, it almost a pass-through as much as possible. However, I just noticed another thing. Your input audio is 32-bit floating point while the output is 16-bit signed integer. It is not enough to simply set the audio output sample format ("sample_fmt=flt" after the "-consumer" in the shell script. You must also change MLT's internal format: add "mlt_audio_format=float" somewhere after "-consumer".

**Comment by hamoid** [comment]
Hi @ddennedy The glitch is only audible with good headphones. I don't notice it with laptop speakers.

I tried the first thing you suggested (removing the transition) and it seems to have fixed the issue!

I wonder why is Kdenlive creating that transition. If you open my Kdenlive project you can see there's really nothing. No effects or transitions or multiple tracks. Just one track with the wav at the beginning.

Should I still try the other things you suggested? I don't know where to finde the "-consumer" you mentioned.

**Comment by ddennedy** [comment]
Closing this as will not fix. This is a side effect of using combine=1 with the mix transition. This was an attempt to provide a mixing algorithm with a simple, automatic approach to prevent attenuation of levels, which turns out to be a difficult problem in DSP. This simple approach inherently introduces artifacts. The workaround is to not use combine=1 and compensate for undesired attenuation levels with audio dynamics filters. Shotcut is moving away from using combine=1.
