### ISSUE TITLE
mlt_playlist_mix producing inconsistant results.

### ISSUE THREAD

**Issue by LeifAndersen** [mltframework/mlt#210]
I have noticed some inconsistent results when using `mlt_playlist_mix`. I have the following program (I've elided some of the error checking) that creates two producers, each with three frames (set with `mlt_producer_set_in_and_out`), and puts both of these producers in a playlist, and mixes in a transition between the two of them with 2 frames: 

```c
#include <stdio.h>
#include <framework/mlt.h>

int main() {
  mlt_factory_init(NULL);
  mlt_profile p = mlt_profile_init(NULL);
  mlt_producer prod = mlt_factory_producer(p, NULL, "vid.mp4");
  mlt_producer_set_in_and_out(prod, 0, 2);
  mlt_producer prod2 = mlt_factory_producer(p, NULL, "vid.mp4");
  mlt_producer_set_in_and_out(prod2, 0, 2);
  mlt_playlist play = mlt_playlist_init();
  mlt_playlist_append(play, prod);
  mlt_playlist_append(play, prod2);
  mlt_playlist_mix(play, 0, 2, mlt_factory_transition(p, "luma", NULL));
  printf("%d\n", mlt_properties_get_int(mlt_playlist_properties(play), "length"));
  return 0;
}
```

Because each of these producers has 3 frames, the playlist without any transition mixed in has 6 frames as expected. (Determined through `mlt_properties_get_int(mlt_playlist_properties(play), "length");`). You would expect that when mixing in a 2 frame transition, the resulting playlist would have 4 frames. 1 from the first clip, 2 from the transition, and 1 from the third. (Using the luma transition here to give a fading effect). However, when I compile and run this example, it returns a playlist with only 2 frames in it.

If instead the transition length was `1`, then the playlist would have 5 frames as expected. (2 for the first producer, 1 for the transition, and 2 for the last producer). And if the transition had 3 frames, the resulting playlist would be 3 frames as expected. (All 3 for the transition).

But a frame count of 2 specifically causes a playlist with 2 frames instead of 4. I am not entirely sure if this is a bug or if I'm just doing something wrong here. I know this example doesn't do any error checking or cleanup, but code that  does that still the same issue.

I should note that the `video.mp4` file comes from: http://techslides.com/sample-webm-ogg-and-mp4-video-files-for-html5

Thoughts?

**Comment by LeifAndersen** [comment]
Yes, this most certainly seems like a off by one error in libmlt. Because when I change the clips to have 4 frames instead of 3, it works as expected.

**Comment by ddennedy** [comment]
Reproduced using `./melt -profile dv_pal color:red out=2 color:blue out=2 -mix 2 -mixer luma -consumer xml:` and viewing the in and out on the lastmost tractor: duration = out - in + 1 = 1 - 0 + 1 = 2.
Whereas `./melt -profile dv_pal color:red out=2 color:blue out=2 -mix 2 -mixer luma -consumer xml:` gives in=0 out=4.

**Comment by LeifAndersen** [comment]
Cool, thanks.

Is there any pre-built nightlies, or is the only way to get it to build from source?

(If building from source is the only way, is there any recommendations for building it on os x?)

**Comment by ddennedy** [comment]
Tomorrow, you should be able to download
http://builds.us.meltytech.s3.amazonaws.com/melt/melt-osx-x86_64-20170306.tar.bz2

Actually, I am not certain how well that works on macOS. Nearly all our other nightly builds work ok on various OSes in a relocatable app fashion, but I do special things to make Shotcut.app work properly for library and resource file location relative to the executable path. Shotcut comes with melt, but it is built without proper support for SDL if you are using melt on the command line and previewing. Otherwise, I will make the URL of the next nightly Shotcut/macOS build public for you.

As for building on macOS, I use MacPorts, and you can use that, for instance, to install mlt and pull in all dependencies (ports intrinsically include build dependencies). Then, uninstall it leaving all dependencies in place, and finally make install a mlt source tree.

**Comment by LeifAndersen** [comment]
Oh cool, I'll try that, thanks.

And ya, I currently use homebrew to install mlt, but that won't get the nightly. But I like that idea, thank you. :)
