### ISSUE TITLE
Failed to dlopen libmltplus.dylib

### ISSUE THREAD

**Issue by 599316527** [mltframework/mlt#244]
Removing the `transition_affine` in plus module fixed the error. And of cause I lost transition affine.

I'm not familiar to C language. I have no idea about the reason why it said "not found mlt_slices_count_normal". `mlt_slices_count_normal` which belongs to  mlt_slices.h should have been included by <framework/mlt.h> indirectly. I'm here to beg for a proper solution to work it out.

```
$ melt -query filters | grep fft
mlt_repository_init: failed to dlopen /usr/local/Cellar/mlt/6.4.1/lib/mlt/libmltplus.dylib
  (dlopen(/usr/local/Cellar/mlt/6.4.1/lib/mlt/libmltplus.dylib, 2): Symbol not found: _mlt_slices_count_normal
  Referenced from: /usr/local/Cellar/mlt/6.4.1/lib/mlt/libmltplus.dylib
  Expected in: /usr/local/Cellar/mlt/6.4.1/lib/libmlt.6.dylib
 in /usr/local/Cellar/mlt/6.4.1/lib/mlt/libmltplus.dylib)
  - avfilter.afftfilt
  - avfilter.fftfilt
```

```
$ cc --version
Apple LLVM version 8.1.0 (clang-802.0.42)
Target: x86_64-apple-darwin16.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by ddennedy** [comment]
The problem is that you have a mixed installation of MLT library (libmlt) and modules. The plus module was modified on Feb 25, 2017 to use the new symbol mlt_slices_count_normal() that is not in V6.4.1 that was released on Nov 15, 2016. Thus, you must have tried to build an unreleased version and installed that to the same location as v6.4.1. Or, perhaps somehow homebrew did that for you, but I do not know homebrew that well. I recommend uninstalling and removing mlt and reinstalling it clean.

**Comment by 599316527** [comment]
Got it. Thank you!
