### ISSUE TITLE
KDENLIVE MLT ERROR

### ISSUE THREAD

**Issue by AV11D724** [mltframework/mlt#259]
I have been having problems with Kdenlive's MLT  as it keeps giving me errors like this: https://hastebin.com/amomanulur.go

You can see it is clearly a problem with one of the .so files, particularly libmltopencv.so where it throws up a n "undefined symbol".

**Comment by ddennedy** [comment]
This is a build problem, or a problem specific to your distribution or system. It is probably not a defect of the code. The nice thing about dynamically loaded libs like this is that they can safely fail to load and the program functions correctly as long as it is not critical. In this case, the opencv plugin only provides tracking features, which you may not be using (advanced feature).

**Comment by AV11D724** [comment]
Id like to let you know this has happened across many distros: from Gentoo to Fedora to Arch Linux to Ubuntu, meanwhile i currently am on Arch. There is another who has had the same problem as me and he close it because he could not get any help with it.

**Comment by AV11D724** [comment]
Also this is what happens when gpu acceleration in Kdenlive is enabled with mlt as well(its causing kde to crash that is why I think this is an mlt problem possibly): https://hastebin.com/ihadisaquv.go

**Comment by ddennedy** [comment]
If you can update the problem report with a more clear and focused subject line and description including some steps, then I will re-open it, and maybe someone will work on and resolve it. If the problem is specifically about the opencv undefined symbol error, then state it as such or re-open the related bug #234 that you mentioned. That bug was closed with no reason; wrong to assume "because he could not get any help with it." Adding unrelated problems such GPU processing in Kdenlive only adds further to the problem that this report as-is reads like a bucket for any and all Kdenlive and MLT bugs, which makes it unfocused and not individually actionable.
