### ISSUE TITLE
Add GIF with loop

### ISSUE THREAD

**Issue by anakrooz** [mltframework/mlt#260]
A GIF input (with a loop) does not loop when played. Many tests but none succeded:
```
- melt anim.gif
- melt anim.gif ignore_loop=0
- melt anim.gif loop=1
- melt anim.gif ignore_loop=0 loop=1
- melt avformat:anim.gif ignore_loop=0 loop=10
```

**Comment by ddennedy** [comment]
Did you try using the melt "repeat" command line option?

**Comment by anakrooz** [comment]
No I didn't. It is a bit better because I succeded to make it work:

Does not work:
```
- melt -repeat 10 anim.gif
- melt -repeat 10 anim.gif out=6
- melt -repeat 10 anim.gif ignore_loop=1
```

Does work but I don't understand why the repeat must be on the end:
```
melt anim.gif out=6 -repeat 10
```

And this does not work but I don't understand why "6" is OK and "5" is not:
```
melt anim.gif out=5 -repeat 10
```

My GIF is composed with 6 frames of 0,25 seconds each.

**Comment by ddennedy** [comment]
> I don't understand why the repeat must be on the end

Because melt options are position sensitive, which is required for being able to try to represent as complex as a multitrack timeline with filters and transitions on a command line.

> I don't understand why "6" is OK and "5" is not

I do not either at this time. Does it work if you do not include "out=__"?

**Comment by anakrooz** [comment]
> I do not either at this time. Does it work if you do not include "out=__"?

No, as I said, it raise an error ("help" message is displayed, why ?):
```
- melt anim.gif -repeat 10 => ERROR
- melt anim.gif ignore_loop=1 -repeat 10 => ERROR
```

This workaround is not fully great, because I must calculate the GIF length and it may be complicated (frames count, or whatever... I don't even know how the length is calculated when differents delays are set between each frame).

**Comment by anakrooz** [comment]
I have tested with the same GIF but with differents and larger delays (1s, 1s, 5s, 0.25s, 0.25s) and the out parameter must be set according to the display framerate and the total duration (about out=1200). 
And the same "6 OK but not 5" problem occurs (I did not found any value that would make the loop work).
So definitely this is not the solution...

Is there a solution or a bug to solve?
My goal is simply to play an animated GIF with a loop and if possible without any complicated calculation.

A simple "`melt anim.gif`" would make the trick.

**Comment by ddennedy** [comment]
We rely upon FFmpeg for animated GIF, which has poor support for animation and seeking. If you run ffprobe against anim.gif, you will see it reports "Duration: N/A." If you play it with ffplay and right-click the window to seek based on the horizontal position of the click, then it does not seek. [Here is a thread](https://video.stackexchange.com/questions/12905/repeat-loop-input-video-with-ffmpeg) that explains some of the complicated workarounds needed in ffmpeg.

If you run `melt avformat:anim.gif -consumer xml` you will see that it comes through with a duration of
`<property name="length">2147483647</property>`
which is the maximum size of a 32-bit integer that we use for frame counts, and
`<property name="seekable">0</property>`
which means it failed the seek-ability test.
As a result, even the melt -repeat option is not reliable because that reuses the producer, which is unable to seek properly. You have to repeat the filename multiple times, each with an out point to control the duration, to make MLT instantiate multiple producers.

We have no plans at this time to add a new producer using something else to provide better support for animated GIF.
