### ISSUE TITLE
Is it possible/reasonable to do all video processing on the GPU?

### ISSUE THREAD

**Issue by unfa** [mltframework/mlt#272]
Hey! 

As far as I know GPU support in MLT is highly experimental (I crashed Kdenlive with that many times). I don't know if this is a good place to ask, but do you think it's feasible and/or desirable to go towards enabling all image processing on the GPU?

A lot of things can be done with GLSL shaders, including image synthesis, and procedural texture generation. 

I'm thinking about OpenGL mostly, as that could probably provide a big performance gain, as GPUs are very fast at crunching pixels.

I don't know if that'd limit the image quality in any way - I don't know if MLT uses a 32-bit float pipeline like Natron, or is it something else?

It it true that throwing most of the work on GPU would enable faster, better realtime playback and faster offline rendering for video in programs like Kdenlive or Shotcut?

How does that relate to the Movit library? Is that basically a way to do what I'm talking about?

Sorry if this is a noob question, I'm curious on how far the performance of open-source NLA video editing can be pushed, because I want to use that and share my knowlege about open-source music production through videos.

**Comment by ddennedy** [comment]
It is not feasible to do all processing on the GPU because you cannot just run any code you want on the GPU and not everyone is writing code the same way. It is possible to do all Shotcut video processing on the GPU by limiting yourself to the filters that use a GPU icon. It is not always faster, especially if there is no image processing required, and some highly optimized C/asm code can work very fast, but usually it is faster where at least a filter and some compositing is required. MLT uses Movit, which does its processing in 16-bit float per color component.
