### ISSUE TITLE
Downscaled screen output for better performance?

### ISSUE THREAD

**Issue by unfa** [mltframework/mlt#288]
I wonder if this is a Kdenlive thing or an MLT thing, so I'd like to ask here. I'm sorry if this is a wrong place to do so.

In Kdenlive even when I use downscaled proxy footage, it still seems to render the frames in full resolution for preview, even when the preview window is shrunk down - it's not faster at all.

I wonder if it's possible to have MLT process the whole image in a smaller resolution to make it faster?

![selection_504](https://user-images.githubusercontent.com/491704/34824177-ba3086ae-f6cd-11e7-8df3-d6752e1e38e6.png)

If it's possible with MLT, I'll talk to Kdenlive developers and ask them if they can implement this and give the user control, as it could be very useful when fluent motion is more important than resolution of the editing preview.

**Comment by ddennedy** [comment]
> I wonder if it's possible to have MLT process the whole image in a smaller resolution to make it faster?

Yes, by using a lower resolution MLT profile or consumer properties for width, height, and aspect ratio. However, there are caveats. The developer needs to ensure that whatever effects are being used can represent spatial parameters in relative units instead of pixel values, or it needs to automatically scale pixel values of applied effects when switching between low and full resolution. And some effects such as WebVfx can make this very difficult due to the richness of the HTML, CSS, and JavaScript toolkit.
It may also be possible to use the ["consumer" producer](https://www.mltframework.org/plugins/ProducerConsumer/) with a MLT XML file. You give it the composition's full resolution producer, but you place that producer into a graph that is running a lower resolution producer. However, that can be very limiting from an app and API perspective because you may be maintaining and manipulating a graph in memory for the composition and connecting that to the consumer. Perhaps some modification of [producer_consumer.c](https://github.com/mltframework/mlt/blob/master/src/modules/core/producer_consumer.c) could somehow accommodate that use case.

**Comment by unfa** [comment]
Thanks! I'll post a question regarding this idea on Kdenlive forums and link here.
