### ISSUE TITLE
Pan and Zoom is missing from kdenlive after updating to mlt-6.6.0-2

### ISSUE THREAD

**Issue by godofgrunts** [mltframework/mlt#297]
After updating mlt from mlt-6.4.1-8 to 6.6.0-2 I have lost pan and zoom in kdenlive (amongst other effects actually)

See https://imgur.com/a/FUjhK for screenshots

**Comment by bmatherly** [comment]
The affine filter is working for me in Shotcut. I would suggest you start with your packager, and then KDENLIVE. We can re-open this issue somebody comes up with a problem that is specific to MLT.

**Comment by bmatherly** [comment]
If you are installing packages, you can complain to your packager. MLT has an internal libebur128 that is enabled by default to avoid problems like this. But some packagers insist on disabling the internal library and linking against external libebur128.

If you are building yourself, you could just use the internal ebur128 so that you don't have to get one more dependency.
