### ISSUE TITLE
Support vertical text layout

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [mltframework/mlt#304]
Some TV programs in Chinese prefer vertical layout for subtitles. If you add support for vertical text layout, you'll make Shotcut satisfy such requests, and making Shotcut awesome.
See the example: https://www.youtube.com/watch?v=udhBDnny2-Q&list=PLq_o2rIpiltaqr5QgdEyL189Q3tjhQdgr&index=110

**Comment by KrasnayaPloshchad** [comment]
In some cases, left-to-right block direction can be used for vertical layout. Here is a sample made by NMTV (Inner Mongolian TV).
http://www.iqiyi.com/w_19rtadq581.html

**Comment by ddennedy** [comment]
Does the Shotcut Overlay HTML filter support this?
Typically, we do not take feature requests, and this lies in that gray area between bug and feature request. So, I will leave it open for now. However, a patch is highly encouraged if you can convince someone in a language region affected to contribute it. Otherwise, it may take a while for a developer to be motivated to figure out how to test and develop this using their western left-to-right language limitations.
