### ISSUE TITLE
GStreamer URIDecodeBin Producer

### ISSUE THREAD

**Issue by Victordmdb** [mltframework/mlt#324]
Hi! Was wondering how challenging it would be to integrate GStreamer URIDecodeBin as a producer for MLT?

The main advantage is that its compatible with far more different types of sources (especially online streams).

I don't have an in-depth understanding of the structural difference between gstreamer and mlt, so I don't know if it's worth the effort to try and implement?

**Comment by ddennedy** [comment]
I do not know because I have not done, and I do not have any development experience with gstreamer. In theory, it is doable, but I am going to take it up personally as libavformat provides a lot. Also, I know the VLMC project has made an integration with libvlc for producers and consumers. In any case, we use Github Issues only for tracking bugs and not for discussions, and feature requests that are not in the form of a pull request are not accepted.
