### ISSUE TITLE
Possible to render on a web browser at run-time?

### ISSUE THREAD

**Issue by regnartim** [mltframework/mlt#328]
Hello, is possible to render MLT in web browser? Maybe WASM? Are there any projects that do this, and if not, what am I missing? I ask because I am interested in rendering some assets and text that are only available at run-time like date and user picture and name. Thank you.

**Comment by ddennedy** [comment]
No, it is not possible. I am not aware of anyone who has attempted it. I do not know what is missing because I has never attempted to port native code to Javascript.
This is not a bug, and we only use Github Issues for bug tracking. You can propose your idea and solicit others to help using the mailing list: https://sourceforge.net/p/mlt/mailman/
