### ISSUE TITLE
python 3 support 

### ISSUE THREAD

**Issue by sergiomb2** [mltframework/mlt#410]
Hello, 

We need port MLT to python 3 or add support to python 3 , python will be EOL more or less soon .

Thanks

**Comment by ddennedy** [comment]
This is already done. See #407 #408 #409 
The bulk of the work is done by SWIG.

**Comment by ddennedy** [comment]
P.S. You may need to edit the build script to change calls to the `python` executable to `python3` depending on your operating environment.

**Comment by sergiomb2** [comment]
OK, Cool , thanks for the information , we will test it soon .

**Comment by sergiomb2** [comment]
any ETA for new version (with python 3 ) ?

**Comment by ddennedy** [comment]
You do not need a new release unless you are a distro manager looking to check some boxes. The real work is already done by SWIG, and our changes consisted only of fixes for the example programs. If you are using an app that uses the MLT python bindings then you do not need a new release, but you may need a new build that was created against python 3 instead of 2.x.
