### ISSUE TITLE
Can webvfx migrate from QtWebKit to Cef ？

### ISSUE THREAD

**Issue by vvck** [mltframework/mlt#422]
QT don't spport QtWebKit for long time, should webvfx can migrate from QtWebKit to Cef?  Cef can use more html5 feature, more powerful and more good compatibility.

**Comment by ddennedy** [comment]
I recently investigated this, and Qt WebEngine does not support extending Javascript as WebVfx requires. I think the same with CEF as well, but I stopped when I learned that it is [incompatible with mingw](https://bitbucket.org/chromiumembedded/cef/issues/2153/windows-add-mingw-eclipse-build-support).

A comment on [another issue](https://bitbucket.org/chromiumembedded/cef/issues/1718/add-cross-compilation-support-to-cef) shows a possible binary workaround. Then, we would have to extend the Javascript for WebVfx, maintain a fork (more than likely), and first build a binary using msvc. Alternatively, port MLT and dependencies to work with msvc and msvcrt. All of that is a huge amount of work and rather kludgy.

Meanwhile, there is a more recent (5.212) [WebKit fork](https://github.com/annulen/webkit) that is maintaining QtWebKit that is being used by many Linux distributions plus mxe and msys2. I have plans to upgrade Shotcut builds to that if I can my Windows build working with it and stable.

**Comment by vvck** [comment]
Yes，I am eager for the update of webvfx.    @ddennedy

**Comment by coolwanglu** [comment]
Hi @ddennedy ,
[Chrome Devtools](https://github.com/ChromeDevTools/devtools-protocol/) may be another option, this is a websocket channel provided in Chrome or Chromium, which allows to control the browser and take screenshots.

[puppeteer](https://github.com/GoogleChrome/puppeteer) provides high-level API on top of devtools protocol. I played with puppeteer, which works quite well. It allows running JS remotely and taking screenshot.

It'd be not difficult to connect webvfx to puppeteer, or directly with Chrome devtools.

Pros
- Easily connect to latest Chrome/Chromium, which means best support to web standards and possible hard accelerated rendering
- Easy/Fast to build: no more build dependencies on qt, webkit or chromium. Some simple websockets library would be enough
- Much better debugging experience. Devtoosl allows attaching to a running Chrome instance. So theoretically we can choose a frame in Shotcut and inspect/debug with a running Chrome in real time.
- A single instance of Chrome/Chromium can be shared for all webvfx filters, each filter just opens a new page. 

Cons
- There might be quite some overhead passing image back and forth via websocket
- Screenshots are always obtained as PNG or JPG, so there's also the overhead for encoding and decoding.
- I didn't find an easy way of passing image data into the browser. We can of course encode it into a string or bytearray.
- I didn't find an easy of way calling webvfx/C++ functions from JS. This can be mitigated by making a standard js library, such that every webvfx HTML needs to include it. (similar to QtWebEngine)

Some of these issues may be resolved by using CEF though. In generally I think CEF would be more beneficial than QtWebkit (despite the building issues), because it doesn't require the Qt framework. I think QtWebkit is convenience for its language bindings, but it's also doable with CEF: https://bitbucket.org/chromiumembedded/cef/wiki/JavaScriptIntegration.md
