### ISSUE TITLE
Slow Playback

### ISSUE THREAD

**Issue by allanrps** [mltframework/mlt#440]
When playing any file with melt the video plays at about 1/4 speed and is quite choppy. This is also the case in the kdenlive preview. Mlt provides no errors and the same files play flawlessly on vlc and ffplay. I recompiled mlt from source but saw no improvement. It seems to be a known issue as I found a thread anout it, but I have found no solution.

**Comment by ddennedy** [comment]
MLT is slower than vlc and ffplay, but it is not a bug. There are many variables that affect it, but you provided no information, as we cannot be bothered to discuss all of them with you. Of course, it should be faster because everything should be faster. But you cannot do multitrack editing with VLC and ffplay; so, you are comparing different things. Also, hardware-accelerated decoding might be a factor, which MLT does not support.

**Comment by allanrps** [comment]
Thanks for the response but that is not the issue. Perhaps I should have titled this differently, the playback is clearly faulty and has nothing to do with system speed. I know what performace can be expected from mlt. I could play a 20x20 clip with no color and the performance would be the same. There are no frames dropping and the payback is very consistently flawed. For what its worth it seems to render fine, so I believe this has to due eith the opengl implementation. Also my machine does not support hardware acceleration so that is also not a factor. 

I do not know what information you need but I am using mlt 6.14.0-5 on an aarch64 system with Arch. I have configured mlt with everything but opencv, ndi, and swfdec. All other fumctions of mlt function properly, only playback seems to be affected.
