### ISSUE TITLE
Extreme slowdown with image sequences

### ISSUE THREAD

**Issue by faridosc** [mltframework/mlt#451]
When trying to play an image sequence (1 frame in length each) I encounter an extreme slowdown in Kdenlive. (Trying to reproduce in Shotcut but couldn't find a way to import image sequences.) The images are an animation exported from Blender as PNG's. 

In Openshot and Olive it seems to work fine, Pitivi crashes, Cinelerras will not test. 

Would appreciate if you could give me a hint on how to debug this and if there is a solution.

**Comment by ddennedy** [comment]
MLT is preferring a qt producer for this and the others are probably using avformat. PNG is known to be slow in both qt and gdk-pixbuf probably because of using libpng. MLT uses qt or pixbuf because of more flexibility to represent an image sequence (starting number, discontinuity). This can be revisited or overridden. I'll get back to you with some command lines for comparison or you can try to formulate them yourself.

**Comment by ddennedy** [comment]
```
time melt -profile atsc_720_25 pixbuf:'/home/ddennedy/Videos/tests/imgseq1000/longimgseq-%05d.png' ttl=1 out=999 -consumer null terminate_on_pause=1 real_time=-1
real	0m29.332s
user	0m28.985s
sys	0m0.368s

time melt -profile atsc_720_25 qimage:'/home/ddennedy/Videos/tests/imgseq1000/longimgseq-%05d.png' ttl=1 out=999 -consumer null terminate_on_pause=1 real_time=-1
real	0m30.970s
user	0m30.606s
sys	0m0.392s

time melt -profile atsc_720_25 avformat:'/home/ddennedy/Videos/tests/imgseq1000/longimgseq-%05d.png' out=999 -consumer null terminate_on_pause=1 real_time=-1
real	0m19.154s
user	0m37.553s
sys	0m0.746s
```
Meanwhile, ffmpeg image2 demuxer has improved expressiveness for image sequences:
```
ffmpeg -h demuxer=image2
ffmpeg version n4.1-64-gbcfd82b0be Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.3.0-27ubuntu1~18.04)
  configuration: --prefix=/home/ddennedy/opt --disable-static --disable-doc --enable-gpl --enable-version3 --enable-shared --enable-runtime-cpudetect --enable-libtheora --enable-libvorbis --enable-libmp3lame --enable-libx264 --enable-libx265 --enable-libvpx --enable-libopus --enable-libjack --enable-libxcb --enable-libpulse
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
Demuxer image2 [image2 sequence]:
image2 demuxer AVOptions:
  -framerate         <video_rate> .D....... set the video framerate (default "25")
  -loop              <boolean>    .D....... force loop over input file sequence (default false)
  -pattern_type      <int>        .D....... set pattern type (from 0 to INT_MAX) (default 4)
     glob_sequence                .D....... select glob/sequence pattern type
     glob                         .D....... select glob pattern type
     sequence                     .D....... select sequence pattern type
     none                         .D....... disable pattern matching
  -pixel_format      <string>     .D....... set video pixel format
  -start_number      <int>        .D....... set first number in the sequence (from INT_MIN to INT_MAX) (default 0)
  -start_number_range <int>        .D....... set range for looking at the first sequence number (from 1 to INT_MAX) (default 5)
  -video_size        <image_size> .D....... set video size
  -frame_size        <int>        .D....... force frame size in bytes (from 0 to INT_MAX) (default 0)
  -ts_from_file      <int>        .D....... set frame timestamp from file's one (from 0 to 2) (default none)
     none                         .D....... none
     sec                          .D....... second precision
     ns                           .D....... nano second precision
```
Kdenlive can switch to using avformat explicitly for an image sequence. Also, I can add some lines to MLT's loader.dict file to contain glob rules to differentiate image sequences from still images, but Kdenlive might expose some things in its UI such as TTL that will need to be removed or changed. One can supply framerate to the avformat like so:
`'avformat:image2:/home/ddennedy/Videos/tests/imgseq1000/longimgseq-%05d.png?framerate=100'`

**Comment by ddennedy** [comment]
Closing as I changed the default producer for image sequences to be avformat in MLT, but I believe a change will be needed in Kdenlive as well and can be done independently of the MLT change.

**Comment by faridosc** [comment]
Thanks Dan! I will pass it on to the Kdenlive devs.

Cheers :)

**Comment by j-b-m** [comment]
There is a problem within ffmpeg to handle timings in image sequences, which makes it unreliable. Duration of the frames is inconsistent and problem can easily be reproduced with the following command:

melt avformat:image2:frame%03d.png?framerate=0.5

This is supposed to play each frame for 2 seconds. However, the first frame is only played during one frame, next frames play as expected for 2 seconds. 

This issue is acknowledged in ffmpeg's documentation : https://trac.ffmpeg.org/wiki/Slideshow (see the lines under "If your video does not show the frames correctly" ). It is recommended to add the ffmpeg's "fps" filter which does not seem available in MLT. Several bugs were reported in FFmpeg's bugtracker for this problem but without real solution apart from that extra filter.

So I am afraid that this is currently not an option for us...

**Comment by ddennedy** [comment]
> There is a problem within ffmpeg to handle timings in image sequences, which makes it unreliable. 

Is this only when trying to use a different frame rate than the image2 demuxer default of 25? If so, then how about to use timewarp producer with avformat? This seems to work OK for me in some brief testing. melt timewarp:
```
$(echo "scale=2; 0.5/25" | bc):avformat:image2:test-%05d.png
```
