### ISSUE TITLE
Environment variable MLT_REPOSITORY ignored on Windows / OSX

### ISSUE THREAD

**Issue by ryno1234** [mltframework/mlt#459]
The environment variable `MLT_REPOSITORY` is ignored on Windows. I'm not sure why. I would like to set it. I'm able to get around this in my aplication that invokes the MLT framework directly by passing in a directory to `mlt_factory_init(const char *directory)` but when invoking `melt.exe` I do not have that luxury. 

The code below seems to only allow this var if the compile-time macro `RELOCATABLE` is set and if the OS is not Windows nor Apple (Linux only?). 

![image](https://user-images.githubusercontent.com/92051/59789009-dac08f80-9281-11e9-931b-9bf3be6c2862.png)

**Comment by ddennedy** [comment]
On Windows you should install your modules in a subdirectory of the executables in lib/MLT. See Shotcut for example. I am unlikely to change this because on Windows people tend to set environment variables globally using control panel, and an app may want or need its version and not some other app's. There is an old app called hahahaha that uses a very old version of MLT and its installer sets this environment variable thereby breaking Shotcut (and possibly yours). If you want a different behavior then submit a patch that avoids the above problem.

**Comment by ddennedy** [comment]
Add a melt command line option?

**Comment by ryno1234** [comment]
@ddennedy, seems like a very reasonable option and would fall inline with the concept of how the MLT framework can be invoked in the first place. The caller specifies the directory, in the case of melt, that's the user at the command line.

**Comment by ryno1234** [comment]
Thank you @ddennedy
