### ISSUE TITLE
avformat-novalidate freezes on first frame

### ISSUE THREAD

**Issue by johnpasquarello** [mltframework/mlt#469]
Hi

I'm getting an issue in melt where if I play a video with the avformat producer it works fine but with the avformat-novalidate it locks on the first frame. For my use case shrinking the time between running the command and seeing pixels is pretty crucial so I'd love to get avformat-novalidate back

**OS:**
Debian 10 stable

**Hardware:**
VMWare VM with 4GB RAM

**Melt versions:**
6.17 compiled from source with build-melt.sh
Also reproduced it with the 6.12 version from the debian repo
I *cannot* repro on my Debian 9 VM with melt version 6.4.1

**Command:**
melt avformat-novalidate:<video file>

I've tried a few different files, they all work with the normal producer but break in the -novalidate one.
I've tried rendering to avformat instead of sdl2 (although I intend to use sdl2)

Interestingly the failure mode is slightly different when I put the video in the home directory vs VMWare's "shared with windows" directory. If it's in the home dir it fails to a white image rather than the first frame of the video.

Attached are the -debug outputs of avformat vs avformat-novalidate
[novalidate.txt](https://github.com/mltframework/mlt/files/3414788/novalidate.txt)
[avformat.txt](https://github.com/mltframework/mlt/files/3414789/avformat.txt)

Thanks :)

**Comment by ddennedy** [comment]
avformat-novalidate was not intended to be used in a standalone fashion like this where you do not provide any supporting information such as stream indexes and length. It was intended to be used in MLT XML files that contain supporting properties after collecting the information: app constructs a graph using avformat, replaces avformat with avformat-novalidate, and then serializes the graph to XML. `avformat-novalidate` needs at a minimum the `length` and `out` properties provided since it cannot determine this information without opening the file and reading part of it (the validate aspect). I am a little surprised that it used to work like this. I guess some things in MLT grew in support of animation and became more dependent upon duration. I am sorry, but I am not planning to try to fix this. Maybe someone else will.

**Comment by johnpasquarello** [comment]
Ah that's really interesting! I'm not surprised that I'm using it off-label. 
I couldn't find any info on it and just assumed this was it's purpose.

If I do provide the length and out params it works as expected (and with very slightly faster load times)
That's a pretty effective workaround for me!

I'd be willing to try to fix it but if finding the length is gonna be slow it seems silly.
