### ISSUE TITLE
mlt_frame_get_image needs a performance improvement?

### ISSUE THREAD

**Issue by faridosc** [mltframework/mlt#498]
I would like to help debug MLT to see if we can improve performance issues. I started using Kdenlive with Hotspot to try to see why the timeline is laggy sometimes. Seem to be related to  mlt_frame_get_image in line 83 of MltFrame.cpp:

mlt_frame_get_image( get_frame( ), &image, &format, &w, &h, writable );

Does this somehow help? Or is there anything I can do to help debug this issues further?

![image](https://user-images.githubusercontent.com/373726/68546879-3f5bc280-03ba-11ea-880e-d55d476d1ec3.png)

Thanks

**Comment by ddennedy** [comment]
`mlt_frame_get_image` is a virtual function that calls a get_image function in producers, filters, and transitions. This is basically just saying that image processing is the most expensive operation. That is completely expected. This tool is unable to determine which image processing routines are the most expensive because C uses function pointers for virtual functions unlike C++, which uses symbols. This is basically an enhancement request to make MLT faster and not a bug. Of course, it should be faster, but this is not specific enough. Most of the image processing code is in FFmpeg and frei0r, but some also in MLT, Qt, and OpenCV. Performance improvement here comes from using:
- SIMD instructions
- slice- or tile-based image processing (MLT and libavfilter already uses slices in some places)
- frame-threading (MLT uses this, but it is the least efficient use of cache memory)
- GPU processing
The things that can help is to submit pull requests in these areas or fix other bugs so other developers can give more attention to optimization.
