### ISSUE TITLE
Trying to speed up part of video, getting just white screen

### ISSUE THREAD

**Issue by DangerD256** [mltframework/mlt#500]
timewarp:2.0:file.mp4 - produces just white screen... 

`melt 21.mp4 in=0 out=15 "timewarp:2.0:21.mp4" in=15 out=45 21.mp4 in=45 -consumer avformat:"out.mp4" vcodec=libx264 vb=5500k ab=128k strict=-2`

 Produced video: dropbox.com/s/7o6t965qcvy9tuz/out2.mp4?dl=0

Any ideas?

**Comment by bmatherly** [comment]
`"timewarp:2.0:21.mp4" in=15 out=45`

One detail that is not intuitive is that when you apply a speed change, the position of frames in the producer will be different than in the original file. In your specific case, since you are doubling the speed, half of the frames will be thrown away. So frame 30 in the original file will become frame 15 in the warped producer.

To get what I think you are trying to accomplish, you should try:
`melt 21.mp4 in=0 out=15 "timewarp:2.0:21.mp4" in=8 out=22 21.mp4 in=45`

**Comment by DangerD256** [comment]
Doesn't work also.
Tried just timewarp:
` melt "timewarp:2.0:21.mp4"  -consumer avformat:"out.mp4" vcodec=libx264 vb=5500k ab=128k strict=-2`
Same just blank video (35 frames, frame count is okay twice less than original video)

**Comment by DangerD256** [comment]
Hmm, just found that on my video from dashcam it worked fine, video from DJI Phantom produces just white screen:
![image](https://user-images.githubusercontent.com/17032489/68826286-e768d880-06a5-11ea-9d69-da5ad49457b5.png)

Video info:
```
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x55f7a913f900] st: 0 edit list: 1 Missing key frame while searching for timestamp: 0
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x55f7a913f900] st: 0 edit list 1 Cannot find an index entry before timestamp: 0.
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '21.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: mp42mp41
    creation_time   : 2019-10-30T15:20:20.000000Z
  Duration: 00:00:02.90, start: 0.000000, bitrate: 49439 kb/s
    Stream #0:0(eng): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709), 1920x1080 [SAR 1:1 DAR 16:9], 49763 kb/s, 30 fps, 30 tbr, 30k tbn, 60 tbc (default)
    Metadata:
      creation_time   : 2019-10-30T15:20:20.000000Z
      handler_name    : ?Mainconcept Video Media Handler
      encoder         : AVC Coding
    Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 253 kb/s (default)
    Metadata:
      creation_time   : 2019-10-30T15:20:20.000000Z
      handler_name    : #Mainconcept MP4 Sound Media Handler

```
Any ideas?

**Comment by ddennedy** [comment]
Not all videos handle the frame-accurate seeking required for this or editing. Certainly variable frame rate will not work but also long GOP with b frames or open GOP are problematic. Sometimes, you need to transcode a video to an edit-friendly format. See Shotcut has this function, and it always converts for the reverse function because that is even more difficult seeking. This is just the way it is, not a bug, and will not be addressed further.

**Comment by DangerD256** [comment]
How can i quickly transcode it to avoid full recompressing?
`vcodec=copy ` will work or need to do full recompressing:
`melt "21.mp4" -consumer avformat:"21.mp4" vcodec=libx264 vb=5500k ab=128k strict=-2`
?

**Comment by DangerD256** [comment]
`melt "21.mp4" -consumer avformat:"21.mp4" vcodec=libx264 vb=5500k ab=128k strict=-2`

After processing and using processed file it still white... 
How I need to transcode it?
