### ISSUE TITLE
framework doesn't build without "ladspa-sdk" package

### ISSUE THREAD

**Issue by rodolforg** [mltframework/mlt#512]
A simple `./configure && make` fails while building:

> cc -I../.. -DARCH_X86_64 -Wall -DPIC   -O2 -pipe -fno-tree-dominator-opts -fno-tree-pre -ffast-math -DUSE_MMX -DUSE_SSE -DUSE_SSE2 -g -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -fPIC -pthread    -c -o factory.o factory.c
factory.c:21:10: fatal error: ladspa.h: No such file or directory
   21 | #include <ladspa.h>
      |          ^~~~~~~~~~

I had to install a package not required by configure.ac : ladspa-sdk .
It does not provide a pkg-config file however (https://packages.debian.org/buster/amd64/ladspa-sdk/filelist)
Maybe use AC_CHECK_HEADER() macro?

**Comment by ddennedy** [comment]
This project does not use autoconf and automake. If you run `configure --help`, it tells you that you can disable the module that detected ladspa.h using `--disable-jackrack`. See `src/modules/jackrack/configure` for the script that detects ladspa.h. I am not going to change anything here and closing this since you have two ways to resolve it yourself: disable it or install a package.

**Comment by rodolforg** [comment]
In that script it checks for ladspa and automatically disable it if it doesn't exist. But only if `$gpl` is set.
Any reason?

**Comment by ddennedy** [comment]
Most of this module is GPLv2 except the jack consumer. So, the `#include  <ladspa.h>` should be surrounded by `#ifdef GPL` in factory.c.  I'll make that change now.
