### ISSUE TITLE
Scaling regression (affine / qtblend transitions) on different aspect ratio

### ISSUE THREAD

**Issue by j-b-m** [mltframework/mlt#521]
The recent changes related to consumer scaling broke affine/qtblend scaling if the source frame has a different aspect ratio (sar) from consumer profile.

To reproduce, use a dv pal wide file and do :

melt -profile atsc_1080p_25 color:red -track dv-pal.mp4 -transition affine geometry="0=0 0 1920 1080"

The dv-pal-wide video will appear horizontally stretched (like if sar was applied afterwards) and goes beyond 1920x1080 boundaries. We probably need to take the frame's sar/dar in our scale_width/scale_height calculations...

**Comment by ddennedy** [comment]
I reproduced this with affine using dv_ntsc, which is easier to see because instead of going beyond the edges, it falls short and shows the red background:
`melt -verbose -profile square_ntsc color:red -track ~/net/media/unsorted/videos/family/cicadas/cicadas-001.dv -transition affine geometry="0=0 0 640 480" -consumer sdl2 scale=0.5`

I have a fix for that (change also broke distort=1).

However, I do not reproduce it for qtblend. The breakage with affine was in how it normally requests the full source image without any automatic scaling and padding, but qtblend does not do that. Reopen with a command line for qtblend if you do.
