### ISSUE TITLE
melt as an appimage?

### ISSUE THREAD

**Issue by DavidGRX** [mltframework/mlt#524]
Dear developers:
     I've trying to install melt from sources, but there are so many dependencies that I'm having different results in different machines (for example, regarding the available filters). 
  I would like to know if having melt 6.18 as an appimage is planned. 

Thanks in advance

David

**Comment by ddennedy** [comment]
melt comes with [Shotcut](https://shotcut.org/), which is bundled in few formats including portable tar, snap, flatpak, and appimage. However, I think appimage is the least convenient since it must be mounted. Portable tar and snap are most convenient.
Also, there is now a Docker [image](https://hub.docker.com/repository/docker/mltframework/melt). I am preparing a new release 6.20.0 today, and this will be soon updated with a tagged version.
