### ISSUE TITLE
The -group switch not working correctly

### ISSUE THREAD

**Issue by xyzxyxzxzxyz** [mltframework/mlt#529]
Trying from https://www.mltframework.org/docs/melt/

```
$ ls
MVI_5521.mov  MVI_5522.mov  MVI_5523.mov  MVI_5524.mov  MVI_5525.mov  MVI_5528.mov  MVI_5530.mov  MVI_5531.mov  MVI_5533.mov 
$ melt -group in=0 out=49 MVI*
```

In result I am getting only 50 frames of the first video 
Expecting "the first 50 frames of all clips that match the wild card pattern"

What I am doing wrong?

P.S. I just noticed that 
```
melt -group in=0 out=49 MVI* -group
```
do what is expected

Why? This is not consistent with the documentation

**Comment by ddennedy** [comment]
Part of the problem is that hardly any one uses `-group` including myself. The other technical problem is that your command line has an implied consumer (`sdl` or `sdl2`), and the group properties get applied to it as well (at the end). Consumers can have in and out points as well. That is especially handy for playing or encoding a portion of a composition. When you added an extra `-group` at the end you reset the properties collection; so, then nothing in a group was applied to the implied consumer.

I will make a change so that group properties are not applied to an implied consumer. This means if you do something like  `melt -group out=49 MVI* -consumer avformat:previews.mp4` you will be back to where you are now because the consumer will have out=49 now as well. You can easily workaround that by reordering: `melt -consumer avformat:previews.mp4 -group out=49 MVI*`.
