### ISSUE TITLE
Playback speed slower than 1

### ISSUE THREAD

**Issue by sandsmark** [mltframework/mlt#541]
Hi!

Both Shotcut and Kdenlive supports playback speeds faster than 1 (i. e. fast forward), but a requested feature is playback speed slower than 1.

I tried naively just adding 0.5 to the array of playback speeds in kdenlive, but when using that the playback just stopped up. Kdenlive sets speed with `Mlt::Producer::set_speed()`.

I tried looking into what the problem in MLT was, and the only obvious wrongness I could find was that the frame property `_speed` was used as a double everywhere except in `mlt_consumer.c` where it is used as an int. Unfortunately fixing that didn't help (I've attached the diff for my attempt, txt because of github limitations).

Is there some other obvious problem/limitation that I've missed, or do you have any hints for where to look/what to fix?

[speed-property-double.txt](https://github.com/mltframework/mlt/files/4438433/speed-property-double.txt)

**Comment by ddennedy** [comment]
producer speed factors into frame position, which is used heavily throughout the framework and applications. See `mlt_types.h` for a typedef of `mlt_position`, which by default is `int32_t`. You can redefine it as double, however, that is unsupported and will break in many places. In particular, the C++ API and mlt_animation do not use mlt_position but only int.  I only kept this alternate definition of mlt_position in the code as a convenient starting point for someone to do the comprehensive work to make it work. There might be some other tricks to make slow playback work such as stretching the audio. As for the stopped playback, I do not know but perhaps that typedef will help but also you should do this experimental testing at a lower level using melt instead of something very complicated such as kdenlive.

**Comment by sandsmark** [comment]
> See mlt_types.h for a typedef of mlt_position, which by default is int32_t. You can redefine it as double, however, that is unsupported and will break in many places.

Yeah, I saw that it was a typedef (digging deeper), but also assumed that wasn't really a viable solution as it would break ABI and whatnot with other applications using MLT.

> There might be some other tricks to make slow playback work such as stretching the audio.

Well, kdenlive already has support for slowing down individual clips, so I could just re-use that I guess. It was just that it seemed so convenient and simple to call set_speed, and since it took a floating point value I hoped there was a simple bug that caused it not to work with < 1.

> you should do this experimental testing at a lower level using melt instead of something very complicated such as kdenlive.

Yeah, I only tested with kdenlive because they have a convenient C array with the different speeds, so I could just replace 1.1 with 0.5. :-)
