### ISSUE TITLE
Timewarp producer with pitch correction breaks rendering audio sync

### ISSUE THREAD

**Issue by j-b-m** [mltframework/mlt#551]
Following a Kdenlive bug report [ https://bugs.kde.org/show_bug.cgi?id=419461 ], I can confirm that pitch correction on the timewarp producer causes audio to lose sync with video on rendering.

As the reporter noted, it looks like each producer with pitch correction misses one frame of audio. If you put like 60 clips in a playlist, you end up having a 2 seconds audio sync issue between audio and video. I have created a simplified project with related video file.
The attached zip file contains:
* sample.mp4: a simple video of 2 wooden sticks touching each other to make a noise.
* simplified.mlt: an MLT playlist consisting of ~60 cuts of the video clip with timewarp and pitch correction - duration is about 35 second in total.

To reproduce the bug, render the playlist with :
melt simplified.mlt -consumer avformat:result.mp4

In the resulting file result.mp4, you will see the audio slowly gets out of sync, at the end (around 30secs), the audio is about 2 seconds before the video, and the last 2 seconds of the file have no audio at all.

[Tests.zip](https://github.com/mltframework/mlt/files/4529907/Tests.zip)

Let me know if any other info is helpful

**Comment by j-b-m** [comment]
It is also interesting to note that if you add any standard video clip after this timewarp sequence, the audio of this new clip (a standard avformat clip - not using timewarp) will also have the 2 seconds offset. So the complete playlist audio pipeline is affected. Disabling pitch correction in the timewarp producers fixes the audio sync issues, but I think this highlights an interesting problem in MLT.

**Comment by bmatherly** [comment]
Thank you for the test case.

I do not think this use case will be able to work with the MLT architecture. The problem is that the pitch filter adds a delay to the audio samples. The first frame out of the filter contains fewer samples than requested. When the filter sees the last frame in the producer, it can flush the last samples that remain in its buffer. But when a playlist is applied, the filter does not know which frame is the last frame that the playlist will request.

Here is a workaround that you can try to see if this provides the desired results:
https://github.com/bmatherly/mlt/commit/5cf2b624a8d610259e7911de81c030bbfd020d9b
But I do not know if this workaround can be adapted to a definitive solution.

This same problem already exists with the samplerate filter because it also adds a delay. The difference is that the samplerate delay is much less and so it would probably be less noticeable.

You can change your MLT file to get the expected results by setting the out points for each of your producers.

For example:
` <producer id="producer64" in="00:00:00.000" out="00:00:37.400">`
would be changed to
` <producer id="producer64" in="00:00:00.000" out="00:00:01.080">`
And so on.

By the way, are you familiar with the blipflash producer? It produces a sequence with coordinated white flash video frames and single frame audio tones. It is useful for measuring lipsync. A blipflash clip that has been processed can be opened in Shotcut and the Audio Waveform Scope can be compared to the video preview on a frame-by-frame basis to see if the lipsync has shifted.

**Comment by ddennedy** [comment]
> You can change your MLT file to get the expected results by setting the out points for each of your producers.

Does that also require your patch, or is it a separate workaround?

**Comment by bmatherly** [comment]
> > You can change your MLT file to get the expected results by setting the out points for each of your producers.
> 
> Does that also require your patch, or is it a separate workaround?

That should not require the patch. It would be good if someone could test it and report back.

**Comment by alriddoch** [comment]
I am the reporter of the original kdenlive bug.

I can confirm that the workaround patch fixes the issue with j-b-m's simplified testcase, but does not seem to fix the issue with my original testcase, which is essentially the same playlist with a higher res input video, and without whatever simplifications j-b-m did.

**Comment by j-b-m** [comment]
Editing the in/out for the producers in the xml playlist does not fix the issue for me. In fact, the timewarp producer does not take into account the "in" set on the producer!!
Take any video clip and do:

melt timewarp:2:video.mp4 in=20 out=30 -consumer avformat:result.mp4

**This will render frames 40-60 of the original video clip.**

Now try the same command to render a playlist:
melt timewarp:2:video.mp4 in=20 out=30 -consumer avformat:result.mlt

Then render the playlist:
melt result.mlt -consumer avformat:result2.mp4
**This will render frames 0-20 of the original clip!**

Playlist file looks like:

```
<producer id="producer0" in="20" out="30">
    <property name="length">38</property>
(..)
<playlist id="playlist0">
   <entry producer="producer0" in="0" out="10"/>
</playlist>
```

**Comment by bmatherly** [comment]
> In fact, the timewarp producer does not take into account the "in" set on the producer!!

Please test if this fixes that particular problem: https://github.com/mltframework/mlt/pull/555

**Comment by j-b-m** [comment]
Thanks for the patch. I can confirm that with your merge request #555, adjusting the producer in and out fixes the rendering in the sample playlist - audio is synced again. However, as noted by the original bug reported, this does not solve our real life Kdenlive playlist. I am still investigating to understand what are the differences, as it seems some other factors seem to trigger this audio sync bug. Will come back to you asap

**Comment by alriddoch** [comment]
I can also confirm that #555 fixes j-b-m's test case, if the test case is updated with adjusted producer out attributes.

In the case of render output from real kdenlive projects, each producer can have multiple playlist entries, so I'm unclear what the in and out attributes for the producer should be changed to. Can someone clarify what the relationship between the in and out of the producer and the in and out of the playlist entry should be? A pointer to some documents would be useful too.

**Comment by j-b-m** [comment]
Ok, took me some time. When using timewarp producer, Kdenlive uses a unique producer for each playlist entry. So this is similar to the sample playlist I attached to this report.

The problem re-appears with a playlist having the in/out edited when you add a "mix" audio transition between the playlist containing the timewarp clips and another track - like for example a background playlist with a color clip with set.test_audio=0, like used in Shotcut or Kdenlive

So it seems the audio transition somehow cancels the "in/out" workaround, not sure why...

**Comment by bmatherly** [comment]
>  I can confirm that with your merge request #555, adjusting the producer in and out fixes the rendering in the sample playlist - audio is synced again.

Thanks. I will merge that. It was obviously a bug.

> The problem re-appears with a playlist having the in/out edited when you add a "mix" audio transition

I have a theory about this. 

Here is an explanation of the filter to help others understand the difficulty here. The rbpitch filter uses the rubberband library. The rubberband library requires that some samples stay in its buffer so that it can use future samples to finish processing them. The number of samples varies from 20ms to 100ms depending on the pitch change and the sampling frequency.

For an example, let's assume 25fps video at 48khz and an audio delay in the rubberband library of 2000 samples (this makes the following example easy).

Here is that the input/output of the filter would look like in this scenario for a 5 frame clip:
```
Frame      In       Out
 1         1920     0      <- 1920 samples in the buffer. 80 more still needed
 2         1920     1840   <- 2000 samples in the buffer. 1840 are able to come out
 3         1920     1920
 4         1920     1920
 5         1920     3920   <- Last frame will flush all remaining samples from the buffer
```

From this example, you can see that the first two frames will reduce the samples in the mix transition and the last frame will surge a bunch of samples into the mix transition. I wonder if the mix transition inserts silence or drops samples to compensate.

I do not know a great solution for this problem. There is not a good way for the rbpitch filter to read extra samples from the producer in order to keep its buffer satisfied.

**Comment by ddennedy** [comment]
How is the result if you initially fill the rubber band buffer with silence?

**Comment by bmatherly** [comment]
That would work fine. It would have the same effect as if I pad the output with silence when a complete frame of audio is not returned from the library. Either way, there would be three side effects:
1) The silence will be on the output during that part of the video
2) The video will still be delayed
3) When the last frame of video is returned, the last audio samples will be lost

It would solve the problem of leaving audio gaps. I will make a patch and people can see how they like it.

**Comment by bmatherly** [comment]
Here is a patch that implements silence padding: https://github.com/bmatherly/mlt/commit/f86ca7bcd6e236d1c36e4bfbb97e7cccc78d621b

It should eliminate the accumulated stackup of delays. It will cause a period of silence between the cuts.

**Comment by ddennedy** [comment]
I think the main usability problem with pre-filling the buffer with padding silence is that if you split up a clip to change the speed in only part of it (very common), there is are audible gaps at the split points.

**Comment by alriddoch** [comment]
I have tried rendering my project with bmatherly/rbpitch_pad and it works astonishingly well. If I focus I can hear the short silences, but it's much less jarring than without pitch correction, and obviously much better than several seconds of desynced audio.

The result with this patch easily meets my requirements for published video.

**Comment by bmatherly** [comment]
I think that the definitive solution for the pitch filter will be a future state where we have something like the chain/link paradigm so that the service can read samples ahead of the frame it is working on.

In the mean time, I would be willing to go with the silence padding patch.

Pros:
* Fits better into the current architecture
* Does not result in audio "gaps" (which can accumulate)
* Give more predictable/consistent results

Cons:
* Always results in an audio delay (which can reach up to 100ms for extreme pitch changes)
* Results in a period of silence at the start of each clip

Any preference from you, @ddennedy ?

**Comment by ddennedy** [comment]
I am OK to go with the padding, but I also wondered if we should try padding using the samples of the first frame instead of silence. Maybe that will better disguise it.

**Comment by bmatherly** [comment]
Here is a patch that will pre-charge the pitch filter with repeated samples to avoid audio gaps: https://github.com/bmatherly/mlt/commit/12bb66017e85a3eacccc143ec40cc620fbcc6938

It sounds OK to me, but could use a second opinion. I think that either the zero-pad or the precharge patch would be better than the current implementation.

**Comment by alriddoch** [comment]
I've re-rendered my recent project with bmatherly/pitch_precharge and done an A B comparison with the output of bmatherly/rbpitch_pad, and I think bmatherly/pitch_precharge sounds slightly better. There isn't much in it from my perspective, and I'd be happy with either solution.

Both zero-pad and precharge are unambiguously much better than the current implementation.

**Comment by ddennedy** [comment]
I want to thank Alistair for the very helpful testing and feedback.

**Comment by j-b-m** [comment]
Thanks to all. I fully agree that anything is better than current situation where we lose audio sync.

**Comment by alriddoch** [comment]
Thank you all for working on this feature, which is very useful to me.

Are you planning to merge one of the fixes into master before the next release?

**Comment by bmatherly** [comment]
I expect that we will merge one of them. I do not know how we will choose which one to merge.
