### ISSUE TITLE
Issue with -filter crop and transition

### ISSUE THREAD

**Issue by DangerD256** [mltframework/mlt#558]
```
melt   \
"1.jpg" length=120 -filter crop center=1  \
"2.mp4" \
-mix 15 -mixer luma \
 -profile atsc_1080p_30  -consumer avformat:"out.mp4"
```
Result:
https://youtu.be/eOMJMrU2QxQ

During transition crop filter stops to work...

**Comment by ddennedy** [comment]
Use `-attach` here instead of `-filter`. `-filter` attaches to the track, and `crop` is not  intended to be used as a track filter since it crops the source media before automatic scaling and padding. For example, Shotcut does not permit using this filter on a track. I reproduced this using `-filter` but not `-attach`.
