### ISSUE TITLE
reproducible audio click in rendering

### ISSUE THREAD

**Issue by j-b-m** [mltframework/mlt#564]
Hi all,
Following a Kdenlive bug report, we have a reproducible audio click issue in MLT, using a 23 fps profile. Original report is here:
https://bugs.kde.org/show_bug.cgi?id=410726

Sample files are here:
https://bugs.kde.org/attachment.cgi?id=128535

And the bug can be reproduced using the sample files with:
melt -profile ./customprofile32 AI_NORM3.WAV -consumer avformat:test4.wav channels=1

Issue seems fps related since using pal or ntsc fps does not reproduce the issue, however this probably means there is something wrong in the audio pipeline.
Attached is a screenshot of the original and rendered audio, where you can easily see the click on the last rendered frame.
![audioclick](https://user-images.githubusercontent.com/108252/82317551-b9ef4580-99ce-11ea-801e-123b3b2daafc.png)

**Comment by ddennedy** [comment]
I found this is due to silence padding in avformat producer:
https://github.com/mltframework/mlt/blob/master/src/modules/avformat/producer_avformat.c#L2810
If I instead do `*samples = size;` here then it removes the slop you see. The silence padding is important for A/V sync since MLT is frame-based. If we do not maintain a total sample count that matches the expected samples for the current position then the audio track will drift (see `mlt_sample_calculator_to_now()`). 

`melt -consumer xml frame_rate_num=23 AI_NORM3.WAV` reports this file is 14 frames at 23 fps. round(1000 / 23 * 14) = 609 ms, but mediainfo reports `AI_NORM3.WAV` is 601 ms. In Audacity when you select that part you point to in your screenshot, it spans 602 - 609 ms. I am a little surprised 0 shows up like that in Audacity. If I change the `memset()` to set the value 0xff then the line for 602-609 ms is at the top. If I memset with 0x80, then it is centered. That is because a7dd1e2d added support for unsigned 8-bit (`mlt_audio_u8`), but this was overlooked.

**Comment by ulatekh** [comment]
Note that I reopened the bug, with another archive that reproduces six loud pops, three of which are easily seen in Audacity.

Find the sample files here:
https://bugs.kde.org/attachment.cgi?id=128621
