### ISSUE TITLE
Improve handling of locales

### ISSUE THREAD

**Issue by Granjow** [mltframework/mlt#580]
At Kdenlive, we regularly have issues with different locales because by default numbers are converted to string using the default locale. A serialised XML file might then contain e.g.

```xml
<property name="meta.media.0.codec.frame_rate">29,97</property>
```

when saved in Germany or Hungary, or 

```xml
<property name="meta.media.0.codec.frame_rate">29.97</property>
```

when saved in the US.

One reason is that MLT uses LC_ALL for serialising to XML and for converting properties to strings (in `char *Properties::get( const char *name )`). Is there a reason for doing so? Applying the locale settings is okay for a UI so the user understands it, but libraries should rely on a well-defined serialisation format.

Another example:

```c++
auto result = filter->set("Amount", 42.4242);
filter->get("Amount");
// Returns "42.4242" or "42,4242" depending on where the user lives
````

I currently see two different solutions:

1. Make methods virtual in mlt++ so they can be overridden. (A bit [like here](https://invent.kde.org/eugster/decimal-separator/-/blob/master/src/SafeFilter.cpp#L16))
2. Do not consider locales at all for serialising and simply always use `C` for LC_ALL

What do you think about this topic @ddennedy ?

**Comment by ddennedy** [comment]
Why? Because a melt command line user reported a bug that numeric strings with commas in them do not work correctly. But MLT properties are not strongly typed, so numeric strings can be serialized to XML as strings unconverted. That implied the XML needs to support it as well. Also, XML is not purely a serialization format. I designed MLT XML to be convenient for manual authoring, so why not support it there too? What could go wrong? We have an expression: the road to hell is paved with good intentions.

Eventually I ran into a problem with Shotcut users who wanted to share projects and decided to [stop using MLT in a locale-aware mode and save XML with only C locale](https://www.shotcut.org/blog/new-release-190615/).

One can simply set `LC_ALL` or `LC_NUMERIC` to "C" after calling `Mlt::Factory::init()` to change MLT's behavior like so
```
Mlt::Factory::init();
::qputenv("LC_ALL", "C");
::setlocale(LC_ALL, "C");
```
If you run melt as a child process, it inherits the environment variable. If you are running melt interactively you need to set the environment variable yourself, of course. This still works in a Qt GUI program - or at least Shotcut - because it seems to acquire the user locale at startup and hang on to that despite the subsequent calls to `setlocale()`.

I will accept a build macro to turn off the locale handling in MLT. However, you will have to then figure out how to handle legacy documents. Shotcut handles this by detecting the locale of the document upon open and changing its runtime behavior:
```
void MltXmlChecker::setLocale()
{
    // Returns whether this document uses a non-POSIX/-generic numeric locale.
    if (m_usesLocale) {
        ::qunsetenv(MLT_LC_NAME);
        ::setlocale(MLT_LC_CATEGORY, "");
    } else {
        ::qputenv(MLT_LC_NAME, "C");
        ::setlocale(MLT_LC_CATEGORY, "C");
    }
}
```
Then, when you close a project or start a new one, it resets per the top code snippet.

**Comment by Granjow** [comment]
Thank you very much, Dan, for this detailed and informative explanation! I will adapt your Shotcut solution for Kdenlive as this appears to be the best solution – especially with regards to legacy documents. We still want to load them :)
