### ISSUE TITLE
The transitions movit.luma_mix don`t work

### ISSUE THREAD

**Issue by wjhtinger** [mltframework/mlt#589]
I use the cmd as below:
melt avformat:./NORM0122.MP4 -track avformat:./NORM0128.MP4 -transition movit.luma_mix softness=0.5 in=50 out=100 a_track=0 b_track=1 reverse=1

But no effect. At same time, I use luma is OK.

I query "transitions", the movit.luma_mix is supported.
 melt -query "transitions"
---
transitions:
  - affine
  - composite
  - luma
  - mix
  - matte
  - region
  - movit.luma_mix
  - movit.mix
  - movit.overlay
  - frei0r.addition
  - frei0r.addition_alpha
  - frei0r.alphaatop
  - frei0r.alphain
  - frei0r.alphainjection
  - frei0r.alphaout
  - frei0r.alphaover
  - frei0r.alphaxor
  - frei0r.blend
  - frei0r.burn
  - frei0r.cairoaffineblend
  - frei0r.cairoblend
  - frei0r.color_only
  - frei0r.composition
  - frei0r.darken
  - frei0r.difference
  - frei0r.divide
  - frei0r.dodge
  - frei0r.grain_extract
  - frei0r.grain_merge
  - frei0r.hardlight
  - frei0r.hue
  - frei0r.lighten
  - frei0r.multiply
  - frei0r.overlay
  - frei0r.saturation
  - frei0r.screen
  - frei0r.softlight
  - frei0r.subtract
  - frei0r.uvmap
  - frei0r.value
  - frei0r.xfade0r
...

So, what's wrong, how can I use movit.luma_mix?

**Comment by ddennedy** [comment]
Read https://www.mltframework.org/docs/opengl/

First, you should add `-verbose` to possibly get more information. It probably fails because it has no OpenGL context. The MLT movit module does not get one on its own it needs something to provide it. For that, `melt` depends on Qt and the MLT `qt` module, but I do not see `qtblend` in your list of transitions suggesting the qt module is not available. if you are not going to use Qt, then you need to invent something to provide the OpenGL context. Again, the OpenGL document above explains more about that.

**Comment by wjhtinger** [comment]
> 
> 
> Read https://www.mltframework.org/docs/opengl/
> 
> First, you should add `-verbose` to possibly get more information. It probably fails because it has no OpenGL context. The MLT movit module does not get one on its own it needs something to provide it. For that, `melt` depends on Qt and the MLT `qt` module, but I do not see `qtblend` in your list of transitions suggesting the qt module is not available. if you are not going to use Qt, then you need to invent something to provide the OpenGL context. Again, the OpenGL document above explains more about that.

Confused.  I only want to use movit services, why I need qtblend? As I know, the movit and qtblend is the equal service, right?
And, how to create OpenGL context for movit ?
