### ISSUE TITLE
Unable to load factory modules

### ISSUE THREAD

**Issue by djnotes** [mltframework/mlt#597]
I just compiled the example code from the [MLT docs page](https://mltframework.org/docs/framework/):   
The code is very simple:   

```
#include <stdio.h>
#include <unistd.h>
#include <framework/mlt.h>

int main( int argc, char *argv[] )
{
    // Initialise the factory
    if ( mlt_factory_init( NULL ) == 0 )
    {
        // Create the default consumer
        mlt_consumer hello = mlt_factory_consumer( NULL, NULL );

        // Create via the default producer
        mlt_producer world = mlt_factory_producer( NULL, argv[ 1 ] );

        // Connect the producer to the consumer
        mlt_consumer_connect( hello, mlt_producer_service( world ) );

        // Start the consumer
        mlt_consumer_start( hello );

        // Wait for the consumer to terminate
        while( !mlt_consumer_is_stopped( hello ) )
            sleep( 1 );

        // Close the consumer
        mlt_consumer_close( hello );

        // Close the producer
        mlt_producer_close( world );

        // Close the factory
        mlt_factory_close( );
    }
    else
    {
        // Report an error during initialisation
        fprintf( stderr, "Unable to locate factory modules\n" );
    }

    // End of program
    return 0;
}
```
Named the file player.c. 
Compiled it:  `gcc player.c -o player -I /usr/include/mlt -l mlt `
When I run `./player`, it gives me this:  

>Unable to load factory modules

Any ideas what this means and how to fix it?

**Comment by ddennedy** [comment]
You have not installed your build of MLT or sourced setenv in your shell. MLT loads modules dynamically, and it does not know where they are until you do one of those two things.

**Comment by arnabc74** [comment]
I am facing the same problem. I did do 

. setenv

and then

./a.out ~/day11A.mp4

(here ~/day11.mp4 is a valid video file).

Got the error 

Unable to locate factory modules

**Comment by ddennedy** [comment]
Please understand the project is approaching 20 years old with not many frequent contributors. As a result, the docs can become rotten and not 100% reliable. Still, they are usually important to grasp concepts. That is common in open source, and the project members rely a little on people reading some of the source to supplement. I will update this example many appear to be following. As for profiles, see this [doc](https://mltframework.org/docs/profiles/). Thus, for the API, the argument is a path to a file, except MLT includes a bunch of profiles whose name you can simply provide: see the output of `melt -query profiles`. These are simply the basenames of these installed files, but since MLT knows where its data directory is it can find them without a full path. This makes it a lot easier to use between installations. You can specify an installed profile by name to use as a close base and then override certain aspect using consumer properties. Hope that helps.

**Comment by Cj-bc** [comment]
Thank you for updating it and explanation about profiles!! It helps a lot.

Yes, I understand that it is hard to maintain documents up-to-date during such a long time and I do not expect 100% reliable document. Even it was a little bit outdated, it gave me enough understanding of MLT framework to start with. As I thought it might be inappropriate to ask to update that documentation, I left memo here so that it might help anyone encountered the same problem and found this issue.
I really appreciate contributors developing and maintaining this huge project.
