### ISSUE TITLE
webvfx build fails on aarch64

### ISSUE THREAD

**Issue by lgbaldoni** [mltframework/mlt#599]
Building webvfx 1.2.0 with mlt 6.22.0 on openSUSE Tumbleweed.
Log snippet [here](https://github.com/mltframework/mlt/files/5006642/webvfx-1.2.0_aarch64.txt).

Unsure if this is an upstream problem, but I thought of reporting it nevertheless.

EDIT: apparently the target in question supports only GLES.

**Comment by ddennedy** [comment]
webvfx is deprecated; I just have not announced that until the next Shotcut build that does not include it. Also, it is a separate project with its own issue tracker. From the look of the log, you are missing appropriate OpenGL headers. I do not know if that is due to architecture or not. It is failing on `GLWidgetRenderStrategy` which is not even used. You would have to define `WEBVFX_GRAPHICSVIEW` in order to use it, but it is off by default. So, you could modify the source to `#if` out the GLWidgetRenderStrategy` in `render_strategy.{h,cpp}`
