### ISSUE TITLE
Segmentation fault ??

### ISSUE THREAD

**Issue by lee149205** [mltframework/mlt#603]
This is my command. Show error "Segmentation fault" . Please help me, thanks

`export DISPLAY=:99.0 MLT_AVFORMAT_PRODUCER_CACHE=128 MLT_PIXBUF_PRODUCER_CACHE=32 && qmelt 1__6c6954fa7863ecd8b316fc27b10d1f55.xml -consumer 1__6c6954fa7863ecd8b316fc27b10d1f55_z169.mp4 pix_fmt=yuv420p preset=veryfast strict=experimental ar=44100 ac=2 acodec=aac vcodec=libx264 vb=1024k ab=192k -verbose -debug`

<img width="714" alt="Screen Shot 2020-08-11 at 5 13 14 PM" src="https://user-images.githubusercontent.com/11714006/89885995-1b056e80-dbf6-11ea-8959-7db36deec586.png">

**Comment by ddennedy** [comment]
It looks like your composition encoded successfully, but it failed when exiting while doing cleanup. This happens frequently when you are using WebVfx. Are you using that since you used `qmelt`? If so, that is deprecated. If not, you would need to identify what in your XML file is causing the problem. Your report is not reproducible with the information provided.
