### ISSUE TITLE
melt play video has distort sound 

### ISSUE THREAD

**Issue by toryzhao** [mltframework/mlt#616]
[test.zip](https://github.com/mltframework/mlt/files/5486495/test.zip)
the attachment is our video, which is normal in ffplay.

**Comment by bmatherly** [comment]
I confirm the distorted sound with this file. If I extract the .aac audio using the "-acodec copy" feature in ffmpeg, the resulting .aac audio plays in melt without the distortion. This test suggests that the problem is with seeking in the file. Perhaps the audio or video timestamps are aligned in a way that does not work the way that MLT needs to seek for each frame.
