### ISSUE TITLE
Passing data between producer and consumer using melted

### ISSUE THREAD

**Issue by gabrieljablonski** [mltframework/mlt#620]
I'm trying to make it possible to pass arbitrary data between melt producers and consumers. The objective is to be able to access file metadata in the consumer, which seems to only be possible in the producer, since the `mlt_frame` available to the consumer carries only the raw image retrieved from the file.

I've managed to make it work between the `avformat` producer and the `decklink` consumer using two different methods.
The first one is to extend the `mlt_frame` struct with new fields and set them after retrieving the image in [`producer_get_image()`](https://github.com/mltframework/mlt/blob/master/src/modules/avformat/producer_avformat.c#L2019) (after `exit_get_image:`), and then accessing them in the [`render()`](`https://github.com/mltframework/mlt/blob/master/src/modules/decklink/consumer_decklink.cpp#L624`) method in the consumer.
The second method is to simply use `mlt_properties_set_data()` on the frame properties instead.

Both methods are working fine when playing a file (`.mp4`, `.ts`, ...) directly, but when using `.melt` files (and consequently the `melt_file` producer), the data starts showing up as null.

My guess is that it has something to do with the fact that this way the `avformat` producer is instantiated nested in the `melt_file` producer, so the `decklink` consumer is not directly connected to it.

I feel like the problem is straight forward enough that I don't need to show any of my modifications directly, but I can if needed.

Are there any obvious changes that can be made so any of these methods work for `.melt` files? 
Or is there another way that I can pass data between producer and consumer?

**Comment by ddennedy** [comment]
The only way to reliably pass data like this is by setting a property whose name starts with "meta." because those are special. Basically, there are a few places in the code base where those are propagated by copying. However, it requires that the property is serializable to do that work. You can pass a custom serializer to `mlt_properties_set_data()` and then deserialize it yourself when you get the property as a string in your consumer. You can set these `meta.` properties on the producer and they should be copied all of the way to the frames received by a consumer.
We only use this space for tracking bugs, and since this is a question I am closing it, but you can still comment.

**Comment by gabrieljablonski** [comment]
That sounds like it will solve my problem just fine. Will post here after I try it out. Thanks in advance for the help.

**Comment by bmatherly** [comment]
You can also access the original producer from the frame. With the original producer handle, you can query properties of the producer. But the query will not necessarily be frame accurate.

https://github.com/mltframework/mlt/blob/master/src/modules/plus/filter_dynamictext.c#L104

**Comment by gabrieljablonski** [comment]
@ddennedy It worked as expected, thanks a lot for the suggestion.
