### ISSUE TITLE
blank window with src/examples/play

### ISSUE THREAD

**Issue by eszlari** [mltframework/mlt#638]
I can compile `src/examples/play` successfully (with configure/make), but when executing it, all I get is blank window that doesn't react to input. I have all modules (apart from movit) enabled. How could I debug this?

**Comment by ddennedy** [comment]
Did you give it a filename? If so, do you hear sound? If so, then this is a duplicate of  #449.
Otherwise, it is normal that it does not react to input. It is not programmed to do that because this is the simplest example possible. It is for developers. Did you read the code? If you expect something like melt use melt.

**Comment by eszlari** [comment]
My bad, I could have inferred from the name "play" that it expects a file as an argument.

**Comment by ddennedy** [comment]
Fixed in cb0ff75
