### ISSUE TITLE
melt not support codec copy?

### ISSUE THREAD

**Issue by zhangqianliang** [mltframework/mlt#72]
melt 001.flv in=00:00:10.000 out=00:00:19.960 -consumer avformat:001.mp4 acodec=copy vcodec=copy

[consumer avformat] audio codec copy unrecognised - ignoring
[NULL @ 00546cc0] [consumer avformat] video codec copy unrecognised - ignoring
AVC: nal size 23330846

**Comment by ddennedy** [comment]
No, it does not, and it will not be added.

**Comment by Fak3** [comment]
This is useful feature. May i ask why this will not be supported?

**Comment by ddennedy** [comment]
Because you did not submit the patch that adds it, it is very difficult to do within the flexibility and expressiveness that MLT provides, one can use ffmpeg today for simple scenarios, and we only use this tracker for defect tracking - not feature requests. Feature requests require personal contact to discuss a contract for paid development.
