### ISSUE TITLE
Make Mlt with Qt5 and Qt6 co-installable

### ISSUE THREAD

**Issue by jlskuz** [mltframework/mlt#801]
The packager of openSUSE said that it would be necessary to make mlt with Qt5 and mlt with Qt6 or at least the modules co-installable. You can find the discussion here: https://invent.kde.org/teams/frameworks-devs/kf6-workboard/-/issues/8#note_457528

However I am a bit lost since I do not have enough knowledge on distro packaging and the insides of MLT's module loading to assess the right approach. Ones something is decided I am happy to help with a merge request.

While writing this I also wonder weather it is really necessary to have them co-installable? Theoretically there should not be an issue to run a Qt5 Shotcut, Kdenlive or what ever with a Qt6 mlt or am I wrong? _(EDIT: probably I am wrong (?) since I just thought of `melt` and forgot about our apps linking to mlt)_

**Comment by ddennedy** [comment]
In the past it was instant death (crash on launch) to mix major Qt versions in the same process. This is based primarily Kdenlive using Qt5 was loading MLT built with the OpenCV module, and the OpenCV libraries were linked to Qt4. This goes a way back, but I would not expect to be able to mix them or at least to trust it. 

This request sounds similar to the SDL1/2 situation where we do have 2 MLT modules. That was not supposed to last long, but Flowblade is still using SDL1. In that case, there was code duplication but also changes. Since we now have the qt module working with both Qt 5 and 6 I do not like the idea of code duplication. There is probably a way to build the module twice with CMake that hopefully is not too much work and ugliness. As for the loading, I think it have to be done with a new environment variable. Maybe instead of being Qt specific, it can be generic like a deny list based on the basename minus the extension. For example, I could use `MLT_REPOSITORY_DENY=libmltsdl:libmltqt` to tell it to skip loading the SDL1 and Qt5 modules.

**Comment by jlskuz** [comment]
Okay, thanks for the feedback!

First step of introducing `MLT_REPOSITORY_DENY``done. I guess ones we have two Qt modules we should make `MLT_REPOSITORY_DENY=libmltsdl:libmltqt6` the default?

**Comment by ddennedy** [comment]
libmltsdl will not be in the default as the dual modules are not problematic in its current state. With Qt it is different because I do not want to have new/differently named services per Qt version.

**Comment by ddennedy** [comment]
fixed in #807
