### ISSUE TITLE
Animated SVG image is not working

### ISSUE THREAD

**Issue by manojmmewara** [mltframework/mlt#891]
I tried to put one animated svg image, but after the rendering of the video animation part of it was missing.
Can you suggest if MLT support any plugin which can do the job as its a very critical feature nowadays considering market trend...
Thanks for your support and for building such a nice platform!!!
[svg image](https://cdn.svgator.com/images/2022/12/10-Christmas-animation-examples-to-spice-up-your-website---freebies-for-the-last-minute.svg)

If you have any suggestions by which i can achieve this that will be a great help !!!

**Comment by ddennedy** [comment]
It is not supported. MLT only supports SVG through libraries, and SVG has bad interoperability in general with animation being the worst because there is JavScript and SMIL animation, and maybe even more now. Authoring tool support is weak too. The market trend is away from SVG animation and toward Lottie and Rive for the web. The MLT gdk module uses librsvg, which does not support animation. The MLT qt modules uses Qt obviously, which does not support it either and only a subset of SVG Tiny. The best direction seems to be Lottie animation and the MLT glaxnimate module, which uses Qt and must be manually enabled. If using git, you need to clone submodules recursively.
