### ISSUE TITLE
Mp3 audio playback broken with recent commit

### ISSUE THREAD

**Issue by j-b-m** [mltframework/mlt#906]
Audio playback of mp3 files is broken with the addition of these 3 lines in avformat cache recent commit:
https://github.com/mltframework/mlt/commit/71cb8271138b8f9aa584f3a03b1705c485cd55a3#diff-dd4dd7f8b6c28984ac8e670241eb3a0e5ddc65efa5c2784a7267a018d6ff6811R3325-R3327

Problem is reproducible with chains, not producers:
`melt -chain audio.mp3`
Audio is only garbage.

Interestingly, the issue is not present if `mute_on_pause` is set to 0:
`melt -chain audio.mp3 mute_on_pause=0`
plays fine.

But since mute_on_pause defaults to 1, this breaks quite a lot of things...

**Comment by bmatherly** [comment]
You are correct. mute_on_pause is not compatible with chains when audio conversion is needed.

The avformat consumer is predicated on the assumption that if audio is requested for the same frame twice in a row then the application is paused. This is no longer a valid assumption since links in a chain may request audio multiple times for other reasons (time remapping, buffering, etc).

I added the "mute_on_pause" property many years ago so the mute behavior could be disabled because the existing behavior did not support displaying audio in the audio meters in Shotcut.
https://github.com/mltframework/mlt/commit/ca97ca2f37ce048d00587e149883ba7472e15fce

I propose that for this next release we do two things:
1) Set the default mute_on_pause=0
2) Deprecate the mute_on_pause property

In the future, we can remove the property altogether.

**Comment by ddennedy** [comment]
> I propose that for this next release we do two things:

I am OK with that.

**Comment by bmatherly** [comment]
This is done now. @j-b-m can you test and report back.

One thing to note is that now when you play something in melt, it will play the same repeated sound at the end of the clip (unless you use terminate_on_pause). If you do not want to hear sound at the end of the clip, you can specify "scrub_audio=0" on the consumer. Maybe that should be the default.

**Comment by ddennedy** [comment]
Or use consumer property terminate_on_pause=1. Melt as a player is low priority.

**Comment by bmatherly** [comment]
> Or use consumer property terminate_on_pause=1

Yes. I agree. I have been tempted to make melt set that by default and make the user override it if they do not want it.

**Comment by ddennedy** [comment]
The only default I agree to change at this time is mute_on_pause.

**Comment by j-b-m** [comment]
Thanks for the quick answere. I can confirm that the issue is fixed !
