### ISSUE TITLE
Exporting AVI format videos is very blurry and clearly mosaic like

### ISSUE THREAD

**Issue by w-wj-07** [mltframework/mlt#966]
Hi all, I found an issue while using MLT. The same video material, when I export it to AVI format, will become very blurry and appear mosaic, and this blurriness will become more blurry as the resolution of the profile configuration increases. However, if I export it to MP4 format, there will be no blurriness or mosaic issues. May I ask what the problem is and how can I solve it? Thank you very much.

This is a video exported to MP4 format with a resolution of 1440p. The video is very clear and has no blurring issues.
https://github.com/mltframework/mlt/assets/75413574/029f3be4-64a4-46f5-9cf7-4f335937a60a
![1440p-mp4](https://github.com/mltframework/mlt/assets/75413574/35e1e4b8-a3e8-44a5-a05a-9459140f3976)

This is a video exported to AVI format with a resolution of 1440p, which is very blurry and has mosaic effects.
![1440p-avi](https://github.com/mltframework/mlt/assets/75413574/e0bd427e-fa8f-4c9f-93cc-fbf4cb6c7e66)

**Comment by w-wj-07** [comment]
I used ffmpeg to print out the information of two videos and found that the encoding parameter of the mp4 video is high profile, while the encoding parameter of the avi video is simple profile. Is simple profile the cause of video blurring? May I ask how to modify the AVI format video? The default export is a high profile, not a simple profile. Can I achieve this by setting the consumer's configuration.
This is the information from AVI video
![avi-info](https://github.com/mltframework/mlt/assets/75413574/e89f6cb3-e437-4c8d-b95c-4032b680d7a5)

This is the information from MP4 video
![mp4-info](https://github.com/mltframework/mlt/assets/75413574/87344fd2-3feb-404e-8721-14da0115bdbc)

**Comment by bmatherly** [comment]
Your links do not work for me and the images are too blurry to read. But High profile works for both mp4 and AVI for me in my simple test. Maybe you did not set the resolution or profile correctly.

The parameters for the avformat producer are here:
https://mltframework.org/plugins/ConsumerAvformat/

I will close this issue because this bug tracker is not available for general support. Please see the support options here and use the appropriate one:
https://mltframework.org/support/
