### ISSUE TITLE
7.22.0 CMakeLists.txt

### ISSUE THREAD

**Issue by GerryHickman** [mltframework/mlt#967]
cmake
Release vs Debug
building as release, warnings display as expected
building as debug, warnings for pure C files are suppressed
~~~
CMakeLists.txt
~~~
around line 150
block of code, triggers on Debug build
~~~
CMAKE_CXX_COMPILER_ID STREQUAL "GNU"
CMAKE_BUILD_TYPE STREQUAL "Debug"
~~~
commenting out this block of code, warnings for pure C files start working again?

**Comment by ddennedy** [comment]
> warnings for pure C files are suppressed

Some yes intentionally as you can read because they are compiler version specific failures that cause compilation to fail when using -Werror which treats warnings as errors. In case you really want to treat ALL warnings as failures then you need to setup a build system with multiple OS, multiple compilers, and multiple versions of the compilers. Then, fix each warning such that it will work on all.  This is what we did, and this is where we landed. If you have a more specific problem to report please do so using sentences.
